spring.application.name=BackEnd
spring.config.import=optional:classpath:application-secrets.properties,\
                     classpath:oauth-atlassian.properties,\
                     classpath:oauth-slack.properties

# for HTTPS
server.port=8443
server.ssl.key-store=${SSL_KEY_STORE}
server.ssl.key-store-password=${SSL_KEY_STORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot-https

spring.mongodb.uri=mongodb://localhost:27017/sutrava

# temporary fix
#server.servlet.session.cookie.same-site=none
#server.servlet.session.cookie.secure=false

#logging.level.org.springframework.security=TRACE
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.data.mongodb=DEBUG